@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

package bronze #D7CCC8 {
    object "[[https://dbdocs.io/github/Footprint?table=arbitrum_transactions&schema=transactions&view=table_structure \n{chain}_transactions]]" as chain_transactions{
        block_timestamp
        block_date
        hash
        block_hash
        block_number
        from_address
        to_address
        value
        gas
        gas_price
    }
}


package silver #F5F5F5 {

    object "[[https://dbdocs.io/github/Footprint?table=contract_info&schema=contract_info&view=table_structure contract_info]]" as contract_info{
        chain
        contract_address
        protocol_slug
    }

    object "[[https://dbdocs.io/github/Footprint?table=protocol_info&schema=protocol_info&view=table_structure protocol_info]]" as protocol_info{
        chain
        protocol_slug
        protocol_name
        protocol_type
        logo
    }

    object "[[https://dbdocs.io/github/Footprint?table=user_indicator_ignore_methods&schema=protocol_transactions&view=table_structure user_indicator_ignore_methods]]" as user_indicator_ignore_methods{
        method_id
        method_name
    }

    object gamefi_info_v2{
        protocol_id
        protocol_name
        protocol_slug
        chain
        logo
    }

    object gamefi_daily_stats{
        day
        protocol_name
        chain
        users
        transactions
        volume
        balance
    }

    object gamefi_add_indicator{
        day
        protocol_name
        social_activity
        popularity
        social_signal
        token_holders
    }

    object gamefi_protocol_slug_mapping{
        protocol_slug_raw
        protocol_slug
    }

    object "{chain}_protocol_transactions" as chain_protocol_transactions{
        chain
        protocol_name
        protocol_slug
        contract_address
        wallet_address
        block_timestamp
        method_id
        tx_hash
        value
    }

}
chain_transactions-->chain_protocol_transactions
contract_info-->chain_protocol_transactions
protocol_info-->chain_protocol_transactions
user_indicator_ignore_methods-->chain_protocol_transactions

package gold #FFECB3 {
    object gamefi_protocol_daily_stats{
        on_date
        chain
        protocol_slug
        protocol_name
        users
        transactions
        volume
    }

    object protocol_daily_stats{
        on_date
        protocol_slug
        protocol_name
        unique_users
        new_users
        total_users
        d1_active_user
        d7_active_user
        d30_active_user
        d180_active_user
        d360_active_user
        d1_new_user
        d7_new_user
        d30_new_user
        d180_new_user
        d360_new_user
    }

    object protocol_transaction_daily_stats{
        on_date
        chain
        protocol_slug
        protocol_name
        unique_users
        new_users
    }

    object protocol_transactions{
      chain
      protocol_name
      protocol_slug
      contract_address
      wallet_address
      block_timestamp
      method_id
      method_name,
      tx_hash
      value
    }

    object protocol_transaction_new_address{
        on_date
        chain
        address
        contract_address
        protocol_slug
    }

    object "[[https://dbdocs.io/github/Footprint?table=protocol_active_address&schema=protocol_transactions&view=table_structure protocol_active_address]]" as protocol_active_address{
        on_date
        chain
        contract_address
        protocol_slug
        wallet_address
        protocol_name
        number_of_transactions
        is_new_address
        protocol_type
    }

}
gamefi_info_v2-->gamefi_protocol_daily_stats
gamefi_daily_stats-->gamefi_protocol_daily_stats
gamefi_add_indicator-->gamefi_protocol_daily_stats
gamefi_protocol_slug_mapping-->gamefi_protocol_daily_stats
protocol_daily_stats-->gamefi_protocol_daily_stats
protocol_transaction_daily_stats-->protocol_daily_stats
protocol_info-->protocol_daily_stats
protocol_transactions-->protocol_transaction_daily_stats
protocol_transaction_new_address-->protocol_transaction_daily_stats
protocol_transactions-->protocol_transaction_new_address
chain_protocol_transactions-->protocol_transactions
protocol_transactions-->protocol_active_address
protocol_transaction_new_address-->protocol_active_address
protocol_info-->protocol_active_address
@enduml