@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

package bronze #D7CCC8 {
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=ethereum_token_transfers \n{chain}_token_transfers]]" as chain_token_transfers
}

package silver #F5F5F5 {
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=contract_info contract_info]]" as contract_info  {
        chain
        protocol_slug
        contract_address
    }
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_collection_info \nnft_collection_info]]" as nft_collection_info {
        collection_slug
        collection_name
        create_at
        first_mint_at
        description
		total_supply (-1 means infinity)
        discord_url
        website_url
        image_url
		telegram_url
        instagram_username
        medium_username
        twitter_username
    }

'    object "nft_collection_attributes" as nft_collection_attributes {
'		--(new)--
'    	collection_slug
'    	chain
'    	contract_address
'        attribute_key
'        attribute_value
'    	attribute_value_rate(-99999999.9 means no setting, count(*)/total group by attribute_key)
'    	total_count(-99999999 means no setting)
'    }

    object "{chain}_{marketplace}_{contract_name}_evt_{match_event}" as mkt_matched_event
    object "{chain}_erc1155_evt_TransferBatch" as transfer_batch_event
    object "{chain}_erc1155_evt_TransferSingle" as transfer_single_event

    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=ethereum_erc721_token_transfers \n{chain}_erc721_token_transfers]]" as chain_721_token_transfers  {
        transaction_hash
        block_timestamp
        block_number
        log_index
        token_address
        from_address
        to_address
        id: string
        amount_raw
        internal_index
    }

    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=ethereum_erc1155_token_transfers \n{chain}_erc1155_token_transfers]]" as chain_1155_token_transfers   {
        transaction_hash
        block_timestamp
        block_number
        log_index
        token_address
        operator
        from_address
        to_address
        id: string
        amount_raw
        internal_index
        type
    }

    object token_price_5min
    object "[[https://dbdocs.io/github/Footprint?table=ethereum_nft_opensea_protocol_marketplace_transactions&schema=nft&view=table_structure \n{chain}_nft_{marketplace_name}_protocol_marketplace_transactions]]" as  protocol_marketplace_transactions {

    }
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_transactions nft_transactions]]" as nft_transactions {
        transaction_hash
        block_timestamp
        block_date
        block_number
        log_index
        chain
        collection_contract_address
        collection_slug
        nft_token_id
        marketplace_contract_address
        marketplace_slug
        number_of_nft_token_id
        value: (USD)
        value_currency: string, default "USD"
        amount
        amount_currency
        amount_currency_contract_address
        buyer_address
        seller_address
        royalty_rate
        royalty_amount
        royalty_value
        platform_fee_rate
        platform_fees_amount
        platform_fees_value
        +trade_type: bundle/single
    }
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_transfers nft_transfers]]" as nft_transfers
    object nft_info  {
        chain
        contract_address
        collection_name
        collection_slug
        image_url
        nft_token_id
        token_name
        mint_transaction_hash
        mint_block_timestamp
        mint_address
        metadata_uri
        metadata : string (to_json)
    }

    object nft_token_attributes  {
        +chain
        +contract_address
        +nft_token_id
        +collection_slug
        attribute_key
        attribute_value
    }
}


contract_info --> mkt_matched_event

transfer_batch_event --> chain_1155_token_transfers
transfer_single_event --> chain_1155_token_transfers

chain_1155_token_transfers --> nft_transfers


package gold #FFECB3 {
    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_collection_latest_stats nft_collection_latest_stats]]" as nft_collection_latest_stats  {
    }

    object nft_collection_transfers_daily_stats{
        on_date
        chain
        collection_contract_address
        number_of_holders
        number_of_transactions
        number_of_mint_transactions
        number_of_burn_transactions
        number_of_transfer_transactions
        total_minted
        total_supply
    }

    object marketplace_nft_collection_daily_stats {
        on_date
        chain
        collection_contract_address
        collection_name
        collection_slug
        marketplace_slug
        marketplace_name
        number_of_buyers
        number_of_sellers
        number_of_sales_transactions
        volume
        liquidity_rate
        max_price
        avg_price
        min_price
        market_cap
        floor_price
    }


    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_collection_daily_stats nft_collection_daily_stats]]" as nft_collection_daily_stats  {
        on_date
        chain
        collection_contract_address
        collection_slug
        collection_name
        number_of_holders
        number_of_buyers
        number_of_sellers
        market_cap
        total_minted
        total_supply
        number_of_transactions
        number_of_mint_transactions
        number_of_burn_transactions
        number_of_sales_transactions
        number_of_transfer_transactions
        volume
        liquidity_rate
        max_price
        avg_price
        min_price
        floor_price
    }

    object "[[https://www.footprint.network/@Footprint/Table-Info-Dashboard?table_name=nft_collection_daily_stats nft_latest_stats]]" as nft_latest_stats  {
        on_date
        chain
        collection_slug
        collection_contract_address
        collection_name
        nft_token_id
        longest_hold_time
        current_hold_time
        date_of_birth
        past_owners
        max_price
        min_price
        avg_price
        number_of_sales
        latest_price
        owner_transfers_time
    }

    object nft_collection_attributes_latest_stats {
    	on_date
        chain
        collection_slug
        collection_contract_address
        collection_name
        attribute_key
        attribute_value
        mint_count
        current_rate
    }
}

nft_token_attributes--> nft_collection_attributes_latest_stats


mkt_matched_event--> protocol_marketplace_transactions
chain_token_transfers --> protocol_marketplace_transactions
chain_token_transfers --> chain_721_token_transfers
token_price_5min -right-> protocol_marketplace_transactions
protocol_marketplace_transactions --> nft_transactions
nft_collection_info --> chain_721_token_transfers
nft_collection_info --> nft_info
nft_info --> nft_token_attributes
chain_721_token_transfers --> nft_transfers
nft_transfers --> nft_collection_transfers_daily_stats
nft_transfers --> marketplace_nft_collection_daily_stats
nft_transactions --> marketplace_nft_collection_daily_stats
nft_collection_transfers_daily_stats --> nft_collection_daily_stats
marketplace_nft_collection_daily_stats --> nft_collection_daily_stats: aggregate all marketplace
nft_collection_daily_stats --> nft_collection_latest_stats

nft_transfers --> nft_latest_stats
nft_transactions --> nft_latest_stats



@enduml
