Project Footprint {
  database_type: 'Doris'
  Note: 'Footprint Data'
}

Table "events"."opensea_ethereum_parse_orders_matched_event" {
    block_timestamp timestamp [note: 'Timestamp of the block where this transfer was in']
    block_number int64 [note: 'transaction happens on which block height']
    transaction_hash string
    log_index int64
    contract_address string
    buyHash string
    sellHash string
    maker string
    price string
    metadata string
}


// ========================= Public =========================


// ========================= NFT =========================
// transaction_hash + log_index
Ref: "nft"."ethereum_nft_opensea_marketplace_transactions".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "nft"."ethereum_nft_x2y2_marketplace_transactions".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "nft"."ethereum_nft_looksrare_marketplace_transactions".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)

Ref: "token_transfers"."bsc_erc721_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "token_transfers"."ethereum_erc721_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "token_transfers"."polygon_erc721_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)

Ref: "token_transfers"."bsc_erc1155_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "token_transfers"."ethereum_erc1155_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)
Ref: "token_transfers"."polygon_erc1155_token_transfers".("transaction_hash",log_index) - "nft"."nft_transactions".("transaction_hash",log_index)

// nft_token_id
Ref: "nft"."nft_transactions".(chain,contract_address,nft_token_id) <> "nft"."nft_daily_stats".(chain,contract_address,nft_token_id)
Ref: "nft"."nft_transactions".(chain,contract_address,nft_token_id) > "nft"."nft_latest_stats".(chain,contract_address,nft_token_id)

// collection_slug
Ref: "nft"."nft_transactions".(chain,contract_address) <> "nft"."nft_collection_daily_stats".(chain,contract_address)


// ========================= Token =========================


// ========================= Address =========================


// ========================= DeFi =========================



