@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam linetype polyline
skinparam linetype ortho

package bronze #D7CCC8 {
    object "{chain}_transactions" as raw_transactions{
        block_timestamp
        hash
        block_hash
        from_address
        to_address
        receipt_contract_address
        input
        value
        receipt_gas_used
        gas_price
    }

    object "{chain}_token_transfers" as raw_token_transfers{
        block_timestamp
        block_hash
        transaction_hash
        from_address
        to_address
        token_address
        value
    }

    object "{chain}_logs" as raw_logs{
        block_timestamp
        block_number
        block_hash
        transaction_hash
        transaction_index
        log_index
        address
        data
        topics
    }
        object "chainlink_token_price_daily" as chainlink_token_price_daily{
        on_date
        token_address
        chain
        token_symbol
        price
    }
    object "coingecko_token_price_daily" as coingecko_token_price_daily{
        on_date
        coin_gecko_id
        token_address
        chain
        token_symbol
        price
    }

    object "token_transfers_v3" as token_transfers_v3{
        block_timestamp
        signature
        block_hash
        block_number
        source
        destination
        mint
        scale
        value
    }

}

package silver #F5F5F5 {

    object "solana_dex_pool_accounts" as solana_dex_pool_accounts{
        pool_address
        pool_name
        token_account
        token_address
        token_symbol
    }

    object "dex_token_price_daily" as dex_token_price_daily{
        on_date
        token_address
        chain
        token_symbol
        price
    }

    object "chain_transactions" as chain_transactions{
        block_timestamp
        block_date
        hash
        block_hash
        block_number
        from_address
        to_address
        value
        gas
        gas_price
    }

    object "{chain}_token_transfers" as chain_token_transfers{
        block_timestamp
        block_date
        block_hash
        transaction_hash
        block_number
        from_address
        to_address
        token_address
        token_symbol
        decimals
        amount_raw
        amount
        value
        token_price
     }

    object "{chain}_logs" as chain_logs {
        block_timestamp
        block_number
        block_hash
        transaction_hash
        transaction_index
        log_index
        address
        data
        topic1
        topic2
        topic3
        topic4
    }

    object "ud_solana_token_transfers" as ud_solana_token_transfers{
        block_timestamp
        block_hash
        transaction_hash
        block_number
        from_address
        to_address
        token_address
        decimals
        value
    }

    object "solana_token_transfers" as solana_token_transfers{
        block_timestamp
        block_date
        transaction_hash
        block_number
        from_address
        to_address
        token_address
        token_symbol
        token_decimals
        amount_raw
        amount
        price
        value
        from_pre_token_balance
        from_post_token_balance
        to_pre_token_balance
        to_post_token_balance
    }
    object "token_price_daily" as token_price_daily{
        on_date
        token_address
        chain
        token_symbol
        decimals
        price
     }

    object "solana_token_price" as solana_token_price{
        on_date
        token_address
        token_symbol
        price
    }
    object "solana_swap_cashflow" as solana_swap_cashflow{
        block_timestamp
        block_date
        transaction_hash
        block_number
        contract_address
        pool_name
        token_0_address
        token_0_symbol
        token_0_value
        token_1_address
        token_1_symbol
        token_1_value
    }

    object "ud_stepn_token_transfers" as ud_stepn_token_transfers{
        block_timestamp
        transaction_hash
        block_hash
        block_number
        from_address
        to_address
        token_address
        token_symbol
        decimals
        amount_raw
        amount
        value
        token_price
    }
}

chainlink_token_price_daily-->token_price_daily
coingecko_token_price_daily-->token_price_daily
dex_token_price_daily-->token_price_daily
token_price_daily-->chain_token_transfers
raw_token_transfers-->chain_token_transfers
raw_transactions-->chain_transactions
raw_logs-->chain_logs
token_transfers_v3-->ud_solana_token_transfers
token_transfers_v3-->solana_token_transfers
solana_token_price-->solana_token_transfers
solana_swap_cashflow-->solana_token_price
token_transfers_v3-->solana_swap_cashflow
solana_dex_pool_accounts-->solana_swap_cashflow
chain_token_transfers-->ud_stepn_token_transfers
chain_transactions-->ud_stepn_token_transfers
token_price_daily-->ud_stepn_token_transfers
@enduml